[collectPlans.JudouMono]
from = ["JudouMono", "JudouMonoFCM"]

[buildPlans.JudouMono]
family = "Judou Mono"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
buildTextureFeature = true

[buildPlans.JudouMono.variants.design]
three = "flat-top-serifless"
five = "oblique-flat-serifless"
seven = "straight-serifed"
eight = "two-circles"
zero = "slashed-split"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing-baseline"
f = "flat-hook-serifless-crossbar-at-x-height"
i = "hooky"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
y = "straight-turn-serifless"
long-s = "flat-hook-serifless"
eszet = "traditional-flat-hook-serifless"
lower-eth = "straight-bar"
lower-iota = "flat-tailed"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "flat-tailed"
partial-derivative = "straight-bar"
cyrl-em = "hanging-serifless"
cyrl-u = "straight-turn-serifless"
asterisk = "turn-hex-low"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
dollar = "open"
cent = "open"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"

[buildPlans.JudouMono.variants.italic]
a = "single-storey-serifless"
d = "toothed-serifless"
f = "flat-hook-tailed"
i = "tailed-serifed"
j = "serifed"
l = "tailed-serifed"
t = "bent-hook-short-neck"
u = "toothed-serifless"
y = "cursive-serifless"
long-s = "flat-hook-tailed"
eszet = "traditional-flat-hook-tailed-serifless"
lower-iota = "tailed"
lower-tau = "tailed"
cyrl-u = "cursive-serifless"
number-sign = "upright"
micro-sign = "toothed-serifless"

[buildPlans.JudouMono.weights.ExtraLight]
shape = 150
menu = 200
css = 200

[buildPlans.JudouMono.weights.Light]
shape = 250
menu = 300
css = 300

[buildPlans.JudouMono.weights.SemiLight]
shape = 350
menu = 350
css = 350

[buildPlans.JudouMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.JudouMono.weights.Medium]
shape = 550
menu = 500
css = 500

[buildPlans.JudouMono.weights.Bold]
shape = 750
menu = 700
css = 700

[buildPlans.JudouMono.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.JudouMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.JudouMono.slopes.Italic]
angle = 8
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.JudouMono.subset.exclude]
ranges = [[119808,119963],[120224,120791],[120802,120831]]

[buildPlans.JudouMono.metricOverride]
sb = 'default_sb * 0.9'
xHeight = 530

[buildPlans.JudouMono.namingOverride]
copyright = 'Copyright 2017-2025 JudouEco. Copyright 2015-2025, Renzhi Li (aka. Belleve Invis, belleve@typeof.net).'
manufacturer = 'JudouEco'
urlVendor = 'https://github.com/JudouEco/'
description = 'A monospace typeface based on Iosevka.'
version = '2.0.0'

[buildPlans.JudouMonoFCM]
family = "Judou Mono FCM"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
buildTextureFeature = true

[buildPlans.JudouMonoFCM.variants.design]
three = "flat-top-serifless"
five = "oblique-flat-serifless"
seven = "straight-serifed"
eight = "two-circles"
zero = "slashed-split"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing-baseline"
f = "flat-hook-serifless-crossbar-at-x-height"
i = "hooky"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
y = "straight-turn-serifless"
long-s = "flat-hook-serifless"
eszet = "traditional-flat-hook-serifless"
lower-eth = "straight-bar"
lower-iota = "flat-tailed"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "flat-tailed"
partial-derivative = "straight-bar"
cyrl-em = "hanging-serifless"
cyrl-u = "straight-turn-serifless"
asterisk = "turn-hex-low"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
dollar = "open"
cent = "open"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"

[buildPlans.JudouMonoFCM.variants.italic]
a = "single-storey-serifless"
d = "toothed-serifless"
f = "flat-hook-tailed"
i = "tailed-serifed"
j = "serifed"
l = "tailed-serifed"
t = "bent-hook-short-neck"
u = "toothed-serifless"
y = "cursive-serifless"
long-s = "flat-hook-tailed"
eszet = "traditional-flat-hook-tailed-serifless"
lower-iota = "tailed"
lower-tau = "tailed"
cyrl-u = "cursive-serifless"
number-sign = "upright"
micro-sign = "toothed-serifless"

[buildPlans.JudouMonoFCM.weights.ExtraLight]
shape = 150
menu = 200
css = 200

[buildPlans.JudouMonoFCM.weights.Light]
shape = 250
menu = 300
css = 300

[buildPlans.JudouMonoFCM.weights.SemiLight]
shape = 350
menu = 350
css = 350

[buildPlans.JudouMonoFCM.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.JudouMonoFCM.weights.Medium]
shape = 550
menu = 500
css = 500

[buildPlans.JudouMonoFCM.weights.Bold]
shape = 750
menu = 700
css = 700

[buildPlans.JudouMonoFCM.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.JudouMonoFCM.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.JudouMonoFCM.slopes.Italic]
angle = 8
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.JudouMonoFCM.subset.exclude]
ranges = [[119808,119963],[120224,120791],[120802,120831],[129232,129240]]

[buildPlans.JudouMonoFCM.metricOverride]
sb = 'default_sb * 0.9'
xHeight = 530

[buildPlans.JudouMonoFCM.namingOverride]
copyright = 'Copyright 2017-2025 JudouEco. Copyright 2015-2025, Renzhi Li (aka. Belleve Invis, belleve@typeof.net).'
manufacturer = 'JudouEco'
urlVendor = 'https://github.com/JudouEco/'
description = 'A monospace typeface based on Iosevka.'
version = '2.0.0'